import '../models/waste_item.dart';
import '../models/marketplace_listing.dart';
import '../models/facility.dart';
import '../models/analysis_result.dart';
import '../models/user_profile.dart';
import '../models/analytics_data.dart';

class MockData {
  static UserProfile get defaultUser => UserProfile(
        id: 'usr_001',
        name: 'Anuj Sharma',
        email: 'anuj@waste2worth.org',
        phone: '+91 98765 43210',
        avatarUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150',
        city: 'Bangalore',
        role: UserRole.individual,
        walletBalance: 3450.0,
        totalWasteRecycledKg: 148.5,
        totalCo2SavedKg: 84.2,
        totalScansCompleted: 29,
        badges: [
          UserBadge(
            title: 'Eco Pioneer',
            description: 'Recycled over 100 kg of domestic scrap',
            icon: '🌱',
            dateEarned: 'Aug 2026',
          ),
          UserBadge(
            title: 'E-Waste Champion',
            description: 'Safely disposed 10+ electronic components',
            icon: '⚡',
            dateEarned: 'Sep 2026',
          ),
          UserBadge(
            title: 'Zero Waste Hero',
            description: 'Consistently recycled for 30 consecutive days',
            icon: '🏆',
            dateEarned: 'Sep 2026',
          ),
        ],
      );

  static List<MarketplaceListing> get initialListings => [
        MarketplaceListing(
          id: 'item_1',
          title: 'Apple iPhone 12 128 GB, Blue',
          price: 45000,
          category: WasteCategory.eWaste,
          location: 'HSR Layout, 24th main road',
          postedTimeAgo: '10 mins ago',
          imageUrls: [
            'https://images.unsplash.com/photo-1605236453806-6ff36851218e?w=800',
            'https://images.unsplash.com/photo-1591337676887-a217a6970a8a?w=800',
          ],
          sellerName: 'Zaire Siphron',
          sellerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
          sellerRating: 4.9,
          brandOrType: 'Apple iPhone',
          conditionOrDefect: '1-2 minor spots on screen',
          warrantyOrCertification: '2 months Warranty',
          accessoriesOrQuantity: 'Original Charger & Box',
          description:
              'Completely unlocked and ready to activate. Has been in a case with screen protector since it came out of the box so it is practically like new. Battery health is at 88%. Great for refurbishment or direct reuse.',
          weightKg: 0.16,
          isFavorite: false,
        ),
        MarketplaceListing(
          id: 'item_2',
          title: 'Robotic Batman Toy',
          price: 2500,
          category: WasteCategory.upcycled,
          location: 'Koramangala, 5th Block',
          postedTimeAgo: '1 hour ago',
          imageUrls: [
            'https://images.unsplash.com/photo-1563089145-599997674d42?w=800',
            'https://images.unsplash.com/photo-1585366119957-e9730b6d0f60?w=800',
          ],
          sellerName: 'Angel Korsgaard',
          sellerAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
          sellerRating: 4.8,
          brandOrType: 'Custom Handcrafted / Metal Scrap Art',
          conditionOrDefect: 'Artisan Repurposed Condition',
          warrantyOrCertification: 'Authentic Upcycled Art Certificate',
          accessoriesOrQuantity: 'Display Stand Included',
          description:
              'Handmade robotic sculpture assembled from salvaged watch gears, computer screws, and copper wires. Sealed with anti-rust coating. Perfect collector desktop sculpture.',
          weightKg: 0.8,
          isFavorite: true,
        ),
        MarketplaceListing(
          id: 'item_3',
          title: 'High-Grade Clean Copper Wire Scrap (12 kg)',
          price: 9600,
          category: WasteCategory.metal,
          location: 'Peenya Industrial Area',
          postedTimeAgo: '2 hours ago',
          imageUrls: [
            'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?w=800',
          ],
          sellerName: 'Rajesh Metallics',
          sellerAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
          sellerRating: 4.9,
          brandOrType: 'Grade-A Millberry Copper Scrap',
          conditionOrDefect: 'Stripped, 99% pure, zero insulation residue',
          warrantyOrCertification: 'Tested Conductivity Certified',
          accessoriesOrQuantity: '12 kg spool bundle',
          description:
              'High purity industrial copper off-cuts stripped from electrical panel rewiring. Ready for immediate smelting or craft smelting. Verified weight with digital scales.',
          weightKg: 12.0,
        ),
        MarketplaceListing(
          id: 'item_4',
          title: 'Baled PET Plastic Flakes / Bottles (50 kg)',
          price: 1500,
          category: WasteCategory.plastic,
          location: 'Whitefield, Outer Ring Road',
          postedTimeAgo: '3 hours ago',
          imageUrls: [
            'https://images.unsplash.com/photo-1618477461853-cf6ed80faba5?w=800',
          ],
          sellerName: 'EcoCycle Hub',
          sellerAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
          sellerRating: 4.7,
          brandOrType: 'Type-1 PET Clear Plastic',
          conditionOrDefect: 'Washed, labels removed, compacted',
          warrantyOrCertification: 'Pollution Board Authorized Recycler',
          accessoriesOrQuantity: '50 kg hydraulic pressed bale',
          description:
              'Clean, sorted beverage bottles suitable for polyester fiber extrusion or rPET pellet manufacturing. Bulk discount available for factory pickups.',
          weightKg: 50.0,
        ),
        MarketplaceListing(
          id: 'item_5',
          title: 'Salvaged Teak Wood Planks & Pallets (8 pcs)',
          price: 3200,
          category: WasteCategory.upcycled,
          location: 'Indiranagar, 100ft Road',
          postedTimeAgo: '5 hours ago',
          imageUrls: [
            'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800',
          ],
          sellerName: 'Urban Salvage Co.',
          sellerAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
          sellerRating: 4.9,
          brandOrType: 'Seasoned CP Teak Demolition Wood',
          conditionOrDefect: 'Nails removed, surfaced on one side',
          warrantyOrCertification: 'Termite Treated',
          accessoriesOrQuantity: '8 planks (6ft x 5inch x 1.5inch)',
          description:
              'Extracted from a heritage villa renovation. Beautiful rich grain, dried and sturdy. Ideal for rustic dining tables, bookshelves, or DIY planters.',
          weightKg: 28.0,
        ),
        MarketplaceListing(
          id: 'item_6',
          title: 'Corrugated Cardboard Cartons (30 kg Lot)',
          price: 480,
          category: WasteCategory.paper,
          location: 'BTM Layout, 2nd Stage',
          postedTimeAgo: '1 day ago',
          imageUrls: [
            'https://images.unsplash.com/photo-1530587191325-3db32d826c18?w=800',
          ],
          sellerName: 'Suresh Kumar',
          sellerAvatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150',
          sellerRating: 4.6,
          brandOrType: '3-Ply and 5-Ply Shipping Boxes',
          conditionOrDefect: 'Dry, flattened, clean condition',
          warrantyOrCertification: 'Zero Moisture Guarantee',
          accessoriesOrQuantity: 'Folded & tied bundles',
          description:
              'E-commerce delivery cartons accumulated over 2 months. Kept in dry indoor storage. Perfect for paper mills or house shifting reuse.',
          weightKg: 30.0,
        ),
      ];

  static List<Facility> get sampleFacilities => [
        Facility(
          id: 'fac_1',
          name: 'GreenEarth Scrap & Recyclers',
          address: 'Plot 42, 14th Cross, HSR Sector 3, Bangalore',
          distanceKm: 1.4,
          type: 'Verified Scrap Dealer (Kabadiwala)',
          rating: 4.9,
          reviewsCount: 142,
          phone: '+91 94480 12345',
          acceptedCategories: [
            WasteCategory.metal,
            WasteCategory.paper,
            WasteCategory.plastic,
            WasteCategory.eWaste,
          ],
          openHours: '08:30 AM - 07:30 PM (Mon - Sun)',
          lat: 12.9141,
          lng: 77.6515,
        ),
        Facility(
          id: 'fac_2',
          name: 'Bengaluru E-Waste Collection Hub',
          address: 'BBMP Ward 174, Koramangala 4th Block',
          distanceKm: 2.8,
          type: 'Authorized E-Waste Drop-off Center',
          rating: 4.8,
          reviewsCount: 89,
          phone: '+91 80 2553 9988',
          acceptedCategories: [
            WasteCategory.eWaste,
            WasteCategory.metal,
          ],
          openHours: '09:00 AM - 06:00 PM (Tue - Sun)',
          lat: 12.9352,
          lng: 77.6245,
        ),
        Facility(
          id: 'fac_3',
          name: 'CleanCity Plastic & Paper Depot',
          address: 'Industrial Layout, Singasandra, Hosur Road',
          distanceKm: 4.2,
          type: 'Municipal Recycling Center',
          rating: 4.6,
          reviewsCount: 65,
          phone: '+91 80 2852 4411',
          acceptedCategories: [
            WasteCategory.plastic,
            WasteCategory.paper,
            WasteCategory.glass,
            WasteCategory.organic,
          ],
          openHours: '07:00 AM - 05:00 PM (Daily)',
          lat: 12.8797,
          lng: 77.6492,
        ),
        Facility(
          id: 'fac_4',
          name: 'Peenya Metal & Alloy Upcyclers',
          address: 'Phase 1, Peenya Industrial Area, Bangalore',
          distanceKm: 9.5,
          type: 'Industrial Scrap Smelter & Upcycler',
          rating: 4.9,
          reviewsCount: 210,
          phone: '+91 98450 77665',
          acceptedCategories: [
            WasteCategory.metal,
            WasteCategory.eWaste,
          ],
          openHours: '08:00 AM - 08:00 PM (Mon - Sat)',
          lat: 13.0285,
          lng: 77.5197,
        ),
      ];

  static List<AnalysisResult> get sampleScans => [
        AnalysisResult(
          id: 'scan_01',
          itemName: 'PET Beverage Bottle (Transparent)',
          category: WasteCategory.plastic,
          confidence: 0.968,
          material: 'Polyethylene Terephthalate (Type 1)',
          recyclability: RecyclabilityStatus.highlyRecyclable,
          estimatedWorthPerKg: 22.0,
          estimatedWeightKg: 0.35,
          totalEstimatedWorth: 8.0,
          co2SavingsKg: 0.45,
          imageUrl: 'https://images.unsplash.com/photo-1618477461853-cf6ed80faba5?w=600',
          recommendations: [
            'Rinse with water and crush flat to conserve bin volume.',
            'Remove the non-PET screw cap if submitting to specialized shredders.',
            'Can be listed in bulk or dropped off at CleanCity Plastic Depot.',
          ],
          disposalGuidelines: [
            'Recycle in Blue Dry Waste Bin.',
            'Do NOT incinerate or discard in compost.',
          ],
          timestamp: DateTime.now().subtract(const Duration(minutes: 15)),
        ),
        AnalysisResult(
          id: 'scan_02',
          itemName: 'Computer Motherboard / PCB Scrap',
          category: WasteCategory.eWaste,
          confidence: 0.942,
          material: 'FR-4 Fiber Resin with Gold & Copper traces',
          recyclability: RecyclabilityStatus.hazardous,
          estimatedWorthPerKg: 180.0,
          estimatedWeightKg: 0.65,
          totalEstimatedWorth: 117.0,
          co2SavingsKg: 3.20,
          imageUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=600',
          recommendations: [
            'High value scrap due to precious metal recovery (Gold/Palladium).',
            'Handle with antistatic gloves; avoid shattering fiberglass board.',
            'Take directly to authorized E-Waste Hub for certificate.',
          ],
          disposalGuidelines: [
            'Classified as hazardous E-Waste.',
            'Never dump in household landfill bins.',
          ],
          timestamp: DateTime.now().subtract(const Duration(hours: 3)),
        ),
        AnalysisResult(
          id: 'scan_03',
          itemName: 'Aluminium Beverage Can Lot',
          category: WasteCategory.metal,
          confidence: 0.985,
          material: 'Alloy 3104-H19 Aluminium Sheet',
          recyclability: RecyclabilityStatus.highlyRecyclable,
          estimatedWorthPerKg: 125.0,
          estimatedWeightKg: 0.80,
          totalEstimatedWorth: 100.0,
          co2SavingsKg: 4.15,
          imageUrl: 'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?w=600',
          recommendations: [
            'Aluminium can be infinitely recycled without loss of quality.',
            'Crush cans to maximize storage efficiency.',
            'Local scrap dealer GreenEarth pays top spot rate today.',
          ],
          disposalGuidelines: [
            'Drop in Metal Scrap stream.',
          ],
          timestamp: DateTime.now().subtract(const Duration(days: 1)),
        ),
      ];

  static AnalyticsReport get sampleAnalytics => AnalyticsReport(
        totalWasteKg: 148.5,
        totalEarningsInr: 3450.0,
        totalCo2SavedKg: 84.2,
        treesEquivalent: 14,
        categoryBreakdown: [
          CategoryBreakdown(categoryName: 'Metal', percentage: 38, weightKg: 56.4, colorValue: 0xFFF59E0B),
          CategoryBreakdown(categoryName: 'E-Waste', percentage: 25, weightKg: 37.1, colorValue: 0xFF8B5CF6),
          CategoryBreakdown(categoryName: 'Plastic', percentage: 22, weightKg: 32.7, colorValue: 0xFF0EA5E9),
          CategoryBreakdown(categoryName: 'Paper', percentage: 15, weightKg: 22.3, colorValue: 0xFF10B981),
        ],
        monthlyTrends: [
          MonthlyStat(month: 'May', earnings: 1200, wasteRecycledKg: 42),
          MonthlyStat(month: 'Jun', earnings: 1850, wasteRecycledKg: 65),
          MonthlyStat(month: 'Jul', earnings: 2100, wasteRecycledKg: 78),
          MonthlyStat(month: 'Aug', earnings: 2900, wasteRecycledKg: 110),
          MonthlyStat(month: 'Sep', earnings: 3450, wasteRecycledKg: 148),
        ],
      );
}
